-- =============================================================================
-- SPOREKART V3 LANDING PAGE CATEGORIES, PRODUCTS & EDUCATIONAL GUIDES SCHEMA
-- =============================================================================

-- 1. Educational Guides Schema (Section 13 Educational Content)
CREATE TABLE educational_guides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(280) NOT NULL UNIQUE,
    summary TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    read_time VARCHAR(50) DEFAULT '5 min read',
    image_url VARCHAR(500),
    display_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Seed Initial Categories if missing
INSERT INTO categories (name, slug, description) VALUES
('Fresh Mushrooms', 'fresh-mushrooms', 'Farm-fresh organic mushroom varieties for culinary and kitchen use.'),
('Dry Mushrooms', 'dry-mushrooms', 'Dehydrated premium gourmet mushrooms with high shelf life and intense flavor.'),
('Spawn Seeds', 'spawn-seeds', 'Autoclaved grain spawn & certified liquid culture syringes for fast colonization.'),
('Mushroom Growing Kits', 'growing-kits', 'All-in-one ready-to-fruit mushroom growing kits for home and commercial growers.'),
('Training & Support', 'training-support', 'Hands-on practical workshops, mycology training, and expert advisory.'),
('Lab Equipment', 'lab-equipment', 'ISO H14 HEPA laminar flow filters, scalpels, auto-claves, and sterile lab tools.');

-- 3. Seed Initial Products
INSERT INTO products (category_id, sku, title, slug, description, base_price, is_active) VALUES
(3, 'SK-LC-OYSTER-10', 'Oyster Mushroom Liquid Culture Syringe (10ml)', 'oyster-mushroom-liquid-culture-syringe-10ml', 'Isolated high-yielding Pleurotus ostreatus strain in 10ml sterile syringe with blunt needle.', 399.00, TRUE),
(3, 'SK-GS-GRAIN-15', 'Autoclaved Grain Spawn Bag with Injection Port (1.5 kg)', 'autoclaved-grain-spawn-bag-15kg', 'Hydrated rye grain autoclaved at 15 PSI for 120 minutes with 0.2 micron filter patch.', 299.00, TRUE),
(4, 'SK-KIT-SHIITAKE', 'Complete Shiitake Mushroom Growing Kit', 'complete-shiitake-mushroom-growing-kit', 'Ready-to-fruit substrate block. Produces fresh Shiitake mushrooms in 7 days.', 899.00, TRUE),
(1, 'SK-FM-BUTTON-250', 'Farm Fresh White Button Mushrooms (250g)', 'farm-fresh-white-button-mushrooms-250g', 'Hand-harvested organic white button mushrooms packed in eco-friendly breathable trays.', 149.00, TRUE),
(2, 'SK-DM-REISHI-100', 'Premium Dried Reishi Slice Pouch (100g)', 'premium-dried-reishi-slice-pouch-100g', 'Sun-dried organic Ganoderma lucidum slices for herbal wellness tea infusions.', 699.00, TRUE),
(6, 'SK-LAB-HEPA-H14', 'Sterile Laminar Flow Hood Filter Unit H14', 'sterile-laminar-flow-hood-filter-unit-h14', '99.99% efficiency HEPA filter unit for sterile culture transfers and inoculations.', 12499.00, TRUE);

-- 4. Seed Initial Educational Guides
INSERT INTO educational_guides (title, slug, summary, category, read_time, image_url, display_order) VALUES
('How to Start Mushroom Cultivation at Home', 'how-to-start-mushroom-cultivation-at-home', 'A beginner-friendly step-by-step roadmap to setting up your first sterile growing space.', 'BEGINNER GUIDE', '5 min read', 'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=600&q=80', 1),
('How to Choose Between Liquid Culture & Grain Spawn', 'how-to-choose-liquid-culture-vs-grain-spawn', 'Learn the difference between mycelium culture syringes and grain spawn bags for optimal yield.', 'CULTIVATION', '7 min read', 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=600&q=80', 2),
('Common Mushroom Growing Mistakes & Contamination Fixes', 'common-mushroom-growing-mistakes-fixes', 'Diagnose green mold, cobweb, over-hydration, and air flow issues before they destroy your flush.', 'TROUBLESHOOTING', '6 min read', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80', 3),
('Setting Up a Budget Still Air Box (SAB) & Clean Space', 'setting-up-budget-still-air-box-clean-space', 'Build a sterile working environment for liquid culture inoculation without high lab equipment cost.', 'LAB SETUP', '8 min read', 'https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=600&q=80', 4);
