-- =============================================================================
-- SPOREKART V4 SUPABASE MEDIA STORAGE & METADATA SCHEMA
-- =============================================================================

CREATE TABLE media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL UNIQUE,
    public_url VARCHAR(500) NOT NULL,
    bucket_name VARCHAR(100) NOT NULL DEFAULT 'sporekart-media',
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    owner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    entity_type VARCHAR(100) CHECK (entity_type IN ('PRODUCT', 'CATEGORY', 'TRAINING', 'ARTICLE', 'USER_AVATAR', 'BANNER', 'GENERAL')),
    entity_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_media_assets_entity ON media_assets(entity_type, entity_id);
CREATE INDEX idx_media_assets_owner ON media_assets(owner_id);

-- Seed initial media assets for catalog products, categories, and educational guides
INSERT INTO media_assets (file_name, file_path, public_url, bucket_name, content_type, size_bytes, entity_type, entity_id) VALUES
('oyster_culture.jpg', 'products/oyster_culture.jpg', 'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=600&q=80', 'sporekart-media', 'image/jpeg', 145200, 'PRODUCT', 1),
('grain_spawn.jpg', 'products/grain_spawn.jpg', 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=600&q=80', 'sporekart-media', 'image/jpeg', 182400, 'PRODUCT', 2),
('shiitake_kit.jpg', 'products/shiitake_kit.jpg', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80', 'sporekart-media', 'image/jpeg', 210500, 'PRODUCT', 3),
('fresh_mushrooms_cat.jpg', 'categories/fresh_mushrooms.jpg', 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80', 'sporekart-media', 'image/jpeg', 195000, 'CATEGORY', 1),
('dry_mushrooms_cat.jpg', 'categories/dry_mushrooms.jpg', 'https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=600&q=80', 'sporekart-media', 'image/jpeg', 160000, 'CATEGORY', 2),
('spawn_seeds_cat.jpg', 'categories/spawn_seeds.jpg', 'https://images.unsplash.com/photo-1595855759920-86582396756a?auto=format&fit=crop&w=600&q=80', 'sporekart-media', 'image/jpeg', 178000, 'CATEGORY', 3);
